version: '3.8'
services:
  nest:
    depends_on:
      - postgres
    restart: always
    build:
      context: .
      target: prod
    init: true
    env_file:
      - .env.docker
    command: npm run start:prod
    ports:
      - "127.0.0.1:3001:3001"
      - "127.0.0.1:9229:9229"

  postgres:
    image: postgres:latest
    env_file:
      - .env.db.docker
    expose:
      - '54320'
    ports:
      - '127.0.0.1:54320:54320'

volumes:
  postgres:
