apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-health-worker-database-secret
  namespace: standalone
spec:
  encryptedData:
    POSTGRES_DB: AgCsjBBOk7hb5fbmnWHQCSPklznmQH9yijt4Ew68//gwAyJHRqpivyTb6PfV+QkNE4YSumLfm60ZbR+qOvLye1qR7W4igcXyC4JKN8M7dChwRk2doxY/+mseDnawCqtOfQDw3DXMABmmscTeGiA/xfDLx7qSoEgGvR8RTCcQmltisFrSrBC9JbUnc+8WPLb48oJvpcTb+b35hP3eYL1Tk9ueTOFfvWhRJgIJo0HgSVa/A7QUGK8dUg7q5S0uaq4QAsJ+mSTYbdkSbwVsF0wobPF5VeKwc3aVx7XKtLA+JiasdvD9HcuwhzFfvgffUxL35s7xBKjXXte09DduCijz1L45kBIWogFe3c/oJragSOHryaUXwqm03hlEY4VhsySkpd7Z7R9IrsmEXHZ5hD+XbQzfnUZzkvpjvyx7fc4+RsfKDS3jiivD+k970N+KncUUonaTWBNyCRTVEu+pwKr/WBwGYNuHUm4lgjogwVtknT5shKI8aGlTn11P/a0QaPckgp2SqS8b3Fp9qNziBtZiw4xrHf1QG0gMqPxy4rAsnXMAcyAfmkNiB9P/1O/OZgA5JNRSJa1eQE88vckYpwXX2m3cjdML+tVZgWVmVMuvqrYHEAH7Aoz9IyVDtaibtArcdv3lgMoQn8BjDFQKHn0RTnERKE7M9vTAe9MVV+dQzvuReVUGX0pRQrFETudFPqAtRsw+0TmaZJPlSfyR
    POSTGRES_PASSWORD: AgCxc4OsONDCDlmDeU+MOAMaXWX31E0rTwcf+13DIYOZ1MwRfWKxpcFdeFkoAADRFZlJN2qm40A4CpRO2zEbwVBp4gWzKQS+VN5DX0eNJN82aKG6kqJI5AJUndJyKgPbTwHCBM17zlENu5pWGxLeOEgfj91RORyq/uTjf/tlUaYHaRVPNmmDUFpnpk19X4FKUj2cEXGZ6IOgFd5qFmNL1AZLsrl0rojzbWY1bcSpMIdD+qrBMP8yNjj3HXw8NtrmNReYHw0pvbX+S0LR2DGuKdASXL20qOQI8Qi4IUDXdULJf9ooxscf79WN/i6d3j0ME88E/5OKKK9QoBPInrrj2h/qLRCmeefNnVcWkw1nAayntgYB/GpEzX++YQnBW21ryNFceNN+OWIhM2sk4PTScvrm9eKHTMVKF4GJz8OdvCahrm9t66n6YcoG/dadqhgS483cP0F4zck65yUtoW2lO/Hl0NmLO/zvMJCQhn7y2DiEMKWS4OkSS0MjGCGUgkjbRNz8jGeaoVxYpLWduo/LSHHaDoPys/0jyaybhcNmdKk0l72tpftnZo3q+0v7vGzwn/5Uat0hsjnYQifflAB9B/gemuekCezzsNYVH+g/5OeO8pwB54HDaD6ItrNNZTGatf0PSqHdlRNvdBYd6qRMh72P7qrwTzO2AIw0gzmqJY6ERWwpvqvPOb6D8nVIlydubxY0iydO+UWch/fnVXq5AwGAGtnbxcWHof2eCKIBls97kzPaSj3MNSGlA29ybgYOKNu4pz1WqL3w1DNLcDk=
    POSTGRES_USER: AgBCRzvMA61v37AL3Z1eGH0bI62BJ8ELCPoDHNwHAh+3OwL+vV23NeT16G7wW3VbSIiit/6saVZ1QHz6VvPUmg8aU/PCsTOkAQjKgfcc1kJC3mmpWADRL7adv2JJ02WPQgK5/1zuTG5NCQe0as85b54+Uqpccb+IJLdx0awx4vhAKmh/SmWUoG/HpwzOTHjYoil9mPtvcocwCtRhOK8kIKyzL1vw10DUYHGPqdz+0v4TIIrvT6WC3YIWZfH/vBNyu8lQbuOzL2zwFaZqSk83+8SLWbur29r4WmeAbnn6yHAIynrpIzTK9BHcGt42HBZ19fZw6MoVHKM+2zFZTQVlyyjYgBgLzXyo+OF/gH25bm5yPcn9TYndNR1Ir7vCUTVIvQJhp0TcLkOmMEDjSioi5nSuLSS2OgDhqagKH7VXhmA/feCX3Ku7d5vpsCAELvjoBEKeLHIHY+RnIWezM5NrAPh5AejL/CAiJjnTUHpAew+Ztl4l0bUCLLlaHsmCKbMFwKO3EuLAf6b8o6Icai2nl5BB9KYE8Wx1YHWsDHe+QJPXl/nNcbeRijQSeED9D6h6Ti3krYa0aSJ+lfExqPtAFIiMjg9GPxjzDwecbhe7JvqleJPhXDT6wn+YFKKYfbhn4vmPVfvslLVPzp/pl23oSwGtAEdX9UC4JiqekeOTvk0upssY41TTwrKwPVhDYu+HOgr6hMLY+li7B2v7
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-health-worker-database-secret
      namespace: standalone

