apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-health-worker-sentry-secret
  namespace: standalone
spec:
  encryptedData:
    SENTRY_DSN: AgBrCFwx7excjj49qTufxxHGqy9bJwg/6329DT7mMgIXLLLlZU4vV10XvwCw9dR5iNpWArMW1PT8JBEEdtzBg/U6ovJzxnRhJxBlKDogd3qhSYTUmCwwA0BHtrw7KTuoRYZyp0g4X/befb1QSoIb9o4kLZlwTRuK20eXuKgt3ei/MRUCMG2uL9cN3eJm7awN7WDENNCvr0ofpqsRtvayXvIEp9ApbDZ1mR3xU1aNuO64Fn4vXms7Z++C5Vheo4u8Zk+4EdAUYIQ3xYn2WpI7uyvzFE6BVfDe10oUWAVw0jjD3tbP7W5YpRIUf9A0Ek/7saYVdApBrfbnpyoxB0e/f4RUnFP5XNFoZ9NzHk9DokpRetTQzY+yOXzQorCrWkoSvGkE5oR6E5y/ZFh0qr0HEzfyfa0cDTPZAeYnWS+4gzEKkKac0IWhZ+f4g2N3DfIBkAfvslmWpa5y944QiMiKrRExZpvC83mG4Py+xO9hndyZf/NuyfXkHiq2hO2DyFwsm3lkrGSQD5gheoVFQB06pPIoLMCVJHObhQYyvzpbSecR2yT2HfzqU/ok/RSdEIfw/6mCo/Qtwh7AaiFwWNyNfu/Jj6yyA5T2DsgzlvzrCwDloQdNzeeOuOof3B0kCZ8vmuxOErfOkMw1K7UxJl4r7kH9YyxJsxtZ2pMpvhU6+Qg7FxDRsPd9VlpiU01sEI1wZyiHgqri8Fcp3eudfy7/Qg2ff+wW8HHgm0MKYJYYCcrG2MWdCQZWIrgDbyvQ5KB9/FWH7JhLhsZ0mjFT0pNO2nEmVM87rui68s0j
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-health-worker-sentry-secret
      namespace: standalone

