apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-health-worker-sentry-secret
  namespace: standalone
spec:
  encryptedData:
    SENTRY_DSN: AgA0wG1ieI21jn7Gx49RMgkFhLv6VS3+wT4n6gLlVr5KiwYBUvBFjWq3VtjX9Sb7QhKIXZnMtxFwvuXyqEeJ7G9E8TcIrPeRzUxZ7dhQQey3oh3INT8vRYwkpeL9aebCp6Wu8+z1janI70JZsOm5RZPU4smtL2fCGImoDShiCY7OE6fzqaHgPVGV8M5GyGj4m2nJxacxLJokZdV38pCE8VyXZq1Hv5EzifUiw4HtUpArzbvfAkZThWWIG8SAXIgUQItYG+PC0uU9iWBt4aRYVRXp7ThTcLeMNJFS/2dZpVQuFWJE5Zj1dGyMzC6s0OSbS6oBpHsStyfHoNWJ/c/gxFk3Pxrr533nFLve3Vko7eknJGFmKOl8fcQIma/wYCdpfTxrqzhjl2kTEnCS/FP0IpltBst/LGVRYuwaCuf7tWInoZiIaKg0glCvbarifiY5vicdP0KdtoGTrAn+TMMZqlGqFnYqr7Bg3HNKHRJT38BOmo50OR/4lJ6vhFtFuWp9/skym8GoJEhL0pllecuIvsuLmlJjWK322jllQPyZprFE7CdNWGovISKBXvk3x4Tf+EGnw6QIIctqtjpzNlULq29vX8SZHtcvFQYyMG/waWo6RAfN5XEvl6HfrbNBdTFP4p79zCYETZAVKHnmwmVbQ/ko3RNs96viRDTR65tbUGzy/vzSocDcL24acHyZvRvnNCjPfZxfw7fmMgUbWN2KICM52VgwWAioxrBbtHfyK0siJUialWP1DsSxWb4Q8dJzywfI9lUG5GPkI9fpEqlcdBhmlxntN8GGe6Y0/oCK11AZhW8X
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-health-worker-sentry-secret
      namespace: standalone

