apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-health-worker-sentry-secret
  namespace: standalone
spec:
  encryptedData:
    SENTRY_DSN: AgBZTjT+IhPdI06885Ypc3mY/a5Q4TsKOTSODrws+pbGN6K2GxT+FKzWB08LH/JJJt4pb819GwvaE1byJ2K1dj2I21AXnUWiTbUIiMSRK1HUBl5xnfQjKFeeI2Jid8e4EkyQ7NSgdOJ3/09msnBDcoVCjvNI5mPwhJ6A6w4PvzSaS98tI2ZGtob3JyKnFFO5LaAK+l2Nm7xOAh+JSPkRFglbvQlu38CN+Eb3nfsyMHGMe9aQlwCE97LpFb7alApSmLHKHXXocQcV2emkVO1KsZrcnMokkU+UcYW5BE/t/r2lgJ0jZl/H1gLAnzXd1fK++EyBgc51K5bHZFdqMIuY8xhTdrcdXLbIHSYzDM0SXgJHcamQhQ5J0aaOVr/gb7KlLUuolEDTipx8VtDV0ikVis2NaAZy7fH0ihVPmEVJuPgwjRzreMD8DfOJzDjaNDQZQoCbygWvNs9ul3kOrlhHOW6VDJEKW5pFTGz9jdPf80fCTXh3H7WOplhBYluJ2IaZ8YQhNmn3uWPA2V2ie/vDalZ9RW3hExy46a2M/LxL4SA8u6bMyG4YCGAJR8bwy1U0YsqX5NSeGozig7WNjw0iqr/TRuahiwrV/APXU3tcU1ayZ3BHvowYO6oZITiDoH+SxfQsmr9vnfJMEavyQCmsjMyE4PmsgDgP0gW8Jwg6S7XarvWH5PRZjy5u5RXvvPqwVWY1IdN5tUbEU38KlBBJV6nIqeKEY/xjlYsCQwmATiVLg1oribAlS/9SMg4zkHH7qxaSF1fQZixJ0PqmU6/ZwSRjCFopMWdu6IYR+qoPvPvB3dAY
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-health-worker-sentry-secret
      namespace: standalone

